### ISSUE TITLE
Remove Header for price data fetching

### ISSUE THREAD

**Issue by Xeonus** [balancer/backend#116]
It would be beneficial if we could remove the requirement for headers with chainId info when using certain queries.

Here is an example if I want to fetch price data for a set of addresses:

```
query TokenGetTokensDynamicData($addresses: [String!]!) {
    tokenGetTokensDynamicData(addresses: $addresses) {
        price
        tokenAddress
        priceChange24h
    }
}
```

I need to provide an array of addresses plus I need to configure the header such as:
```
context: {
            headers: {
                chainId: chainId
            }
}
```

Ideally, the API should be able to resolve pricing for a set of addresses without the need of providing a chain ID header. It works for mainnet but for other networks I need to specifically provide the chainId.

**Comment by gmbronco** [comment]
If I understand right, you are looking for a way to fetch prices for a set of addresses, not necessarily linked to any chain? So for example the filter param could be a mix of addresses from different chains?

Since most token addresses are unique per chain it makes sense to use chains filter only for these edge cases where we absolutely want to narrow it down to a specific one.

**Comment by franzns** [comment]
This query should be extended to also allow a chain to be passed as the param instead of the header.

**Comment by Xeonus** [comment]
Agree with @franzns that probably the most clean solution would be to pass the chain as a param
