### ISSUE TITLE
SOR - Deprecate queryBatchSwap and callData in favor of SOR<>SDK flow

### ISSUE THREAD

**Issue by johngrantuk** [balancer/backend#1177]
Franz found this on the backend repo. Need to investigate and fix.

// TODO for v3 we need to update per swap path
        let queryOutput: ExactInQueryOutput | ExactOutQueryOutput | undefined = undefined;
        let updatedAmount: TokenAmount | undefined = undefined;
        const sdkSwap = new Swap({
            chainId: parseFloat(chainToIdMap[chain]),
            paths: paths.map((path) => ({
                protocolVersion,
                vaultVersion: protocolVersion,
                inputAmountRaw: path.inputAmount.amount,
                outputAmountRaw: path.outputAmount.amount,
                tokens: path.tokens.map((token) => ({
                    address: token.address,
                    decimals: token.decimals,
                })),
                pools: path.pools.map((pool) => pool.id),
            })),
            swapKind,
        });

**Comment by brunoguerios** [comment]
The SOR has a boolean input called `queryBatchSwap`, which will query the swap and update the expectedAmountOut/expectedAmountIn for the paths found when set to true.
It was implemented to handle only the total swap amount in/out, instead of each individual path amount.
The SDK gets the SOR response and query its own result separately (without using the `queryBatchSwap` flag)
And I don't think this is actually being used anywhere - would be nice to double check that.
If that's the case, that change mentioned in the issue may not be needed.
We could even take the opportunity and remove that `queryBatchSwap` boolean and this whole logic from the SOR/backend.

**Comment by johngrantuk** [comment]
> The SOR has a boolean input called `queryBatchSwap`, which will query the swap and update the expectedAmountOut/expectedAmountIn for the paths found when set to true. It was implemented to handle only the total swap amount in/out, instead of each individual path amount. The SDK gets the SOR response and query its own result separately (without using the `queryBatchSwap` flag) And I don't think this is actually being used anywhere - would be nice to double check that. If that's the case, that change mentioned in the issue may not be needed. We could even take the opportunity and remove that `queryBatchSwap` boolean and this whole logic from the SOR/backend.

Wasn't totally clear on this - I think you're saying we need to find out if `queryBatchSwap` is being used by FE team?

**Comment by brunoguerios** [comment]
> Wasn't totally clear on this - I think you're saying we need to find out if `queryBatchSwap` is being used by FE team?

Yeah, I meant the FE 👍
Not sure if anyone else is consuming our api.

And even if the FE is indeed using the flag, maybe they could adapt and use the SDK instead so we don't need this extra logic in the backend

**Comment by brunoguerios** [comment]
Looking at the [FE repo](https://github.com/balancer/frontend-monorepo/blob/0989dcaf0cdbceafa76ab02b2674152b53e75b47/packages/lib/modules/swap/handlers/DefaultSwap.handler.ts#L18), they are already querying directly from the SDK.
I'll go ahead and remove that logic from the SOR.

**Comment by brunoguerios** [comment]
@franzns mentioned that there is an aggregator using `queryBatchSwap` logic from the SOR, so we can't simply remove it.

Taking a step back, there are a few nuances to this issue.

For context, the main issue is that when `queryBatchSwap` is set to true, the output of the query is used only to update total input/output amounts, while each individual path amount is currently not updated.

This affects a few SOR outputs in the context of v3, such as: `callData`, `priceImpact` and `paths` because they end up being built with off-chain math/state. This is unsafe as we can't guarantee an exact match between them.

Here's how I believe we should approach each of them:
1. `callData` -> it's trivial to forward callData from SDK, the current complexity comes from the fact that we're providing `callData` even when `queryBatchSwap` is set to false, because we have to recreate logic to update pathAmounts individually. If we provide `callData` only when `queryBatchSwap` is set to true, we can leverage the SDK and get it all from there. I believe we should restrict callData to be returned only when `queryBatchSwap` is set to `true`
2. `callData` is only returned if `callDataInput` is provided as input. This will be a problem when aggregators start using the SOR for v3, because `callDataInput` requires `sender` and `recipient` to be provided, which is not expected in v3. So, instead of requiring `callDataInput`, I'll simply attach an error message to `callData` for v2 when no `callDataInput` is provided.
3. `priceImpact` -> we could adapt the current ABA implementation to work with v3, but since this is not being used by the FE, I suggest we move the approach to USD values, so eventually the FE can decide to use it. I'll create a separate issue/task to keep track of this
4. `paths` -> it should be straightforward to update it with updated `pathAmounts`. I'll do it on this PR.

**Comment by franzns** [comment]
Thanks a lot Bruno for investigating. I agree with the points, but a few comments:

> 1. `callData` -> it's trivial to forward callData from SDK, the current complexity comes from the fact that we're providing `callData` even when `queryBatchSwap` is set to false, because we have to recreate logic to update pathAmounts individually. If we provide `callData` only when `queryBatchSwap` is set to true, we can leverage the SDK and get it all from there. I believe we should restrict callData to be returned only when `queryBatchSwap` is set to `true`

Instead of only returning calldata when queryBatchSwap is true, we should just run a query batch swap regardless of the flag provided.

> 2. `callData` is only returned if `callDataInput` is provided as input. This will be a problem when aggregators start using the SOR for v3, because `callDataInput` requires `sender` and `recipient` to be provided, which is not expected in v3. So, instead of requiring `callDataInput`, I'll simply attach an error message to `callData` for v2 when no `callDataInput` is provided.

This was done like this to make sure we dont need to unnecessarily calculate callData when it was not requested. This is kind of hacky anyway. I'd propose to remove this condition and build and create callData in any case. If not enough input was provided, we should add an attach that as an error message inside callData as you suggested

In general, the API is not like the SDK, there is no versioning. Removing things is not as easy as just bumping a version. We are effectively breaking integrations when we remove things. The proper path to remove something is to deprecate the function/field/query, wait some time and remove it after.

**Comment by brunoguerios** [comment]
> Instead of only returning calldata when queryBatchSwap is true, we should just run a query batch swap regardless of the flag provided.

Isn't that inefficient? I mean, FE would end up performing an onchain call that would slow down the response and would not be used. Since we're always aiming for more performance, this seems to go a bit on the opposite direction.

**Comment by brunoguerios** [comment]
Just registering the decision of deprecating `queryBatchSwap` and `callDataInput` inputs from SOR request and `callData` from SOR response in favor of using the SDK for querying on-chain state and building `callData`.

Our suggestion to whoever wants to build swap callData from Balancer SOR response is to follow the SOR <> SDK flow described [here](https://docs-v3.balancer.fi/integration-guides/swapping/swaps-with-sor-sdk.html).

For context, only a single aggregator (Balmy) was currently fetching callData directly from the SOR response and they agreed to follow the suggested approach.
