### ISSUE TITLE
Change coingecko unauthorized queries

### ISSUE THREAD

**Issue by franzns** [balancer/backend#58]
Coingecko is deprecating their public API:

![Image](https://github.com/balancer/backend/assets/93920061/a11830b4-d244-40b8-9749-14ba52a5a6c5)

https://support.coingecko.com/hc/en-us/articles/21880397454233-User-Guide-How-to-sign-up-for-CoinGecko-Demo-API-and-generate-an-API-key-

Need to change the test deployment where we use this.

**Comment by franzns** [comment]
Also check coingecko price fetching on old API

**Comment by gmbronco** [comment]
* turns out we use a production key in canary, so that's not an issue.
* in the old API coingecko will start failing, but it's not use for anything at the moment, since it's a fallback for the API. SOR needs a price source for gas price in token estimate for finding optimal path including the gas cost. I replaced coingecko with dynamoDB service.
