### ISSUE TITLE
Investigate subgraph syncs for v3

### ISSUE THREAD

**Issue by franzns** [balancer/backend#72]
Subgraph endpoint: https://api.studio.thegraph.com/proxy/24660/balancer-sepolia-v3/version/latest/

**Comment by gmbronco** [comment]
* Support for proxied data from subgraph + RPC / pricing
* Function naming style

**Comment by gmbronco** [comment]
Subgraph will have two parts:
1. Main – with static data – deployed once and stays true forever
2. Pools – updated as new pools are added – lightweight for resyncing

Main URL: https://api.studio.thegraph.com/query/24660/balancer-sepolia-v3/03147c7c
Pools – not yet deployed

**Comment by gmbronco** [comment]
Hey @mendesfabio let's use this issue to coordinate, because slack messages get lost. We will collab all together here. Let us know when pools are deployed.

**Comment by mendesfabio** [comment]
hey! so the current Subgraphs URLs are:

 - Vault: https://api.studio.thegraph.com/query/31386/balancer-v3-sepolia/version/latest
 - Pools: https://api.studio.thegraph.com/query/31386/balancer-pools-v3-sepolia/version/latest
 
To unblock you I went ahead with a simplified version of the pools one (with only `Pool` and `Factory` entities). I'm still thinking a lot about schema and manifest design and how it affects the new deployments.

What you're looking for is the `weights` attribute at `Pool` entity -- see [example](https://api.studio.thegraph.com/proxy/31386/balancer-pools-v3-sepolia/version/latest/graphql?query=%7B%0A%09pools+%7B%0A%09++id%0A++++factory+%7B%0A++++++id%0A++++++type%0A++++++version%0A++++%7D%0A++++weights%0A%09%7D%0A%7D) query. Note I've moved `type` and `version` (formers `poolType` and `poolTypeVersion`) to this new `Factory` entity but that's also still something I'm pondering. Another thing I want to highlight is, since `weights` is a list at the `Pool` entity, you have to ensure your tokens are sorted in the same way they were registered - I've added a `index` attribute for this and you can see its use on this [example](https://api.studio.thegraph.com/proxy/31386/balancer-v3-sepolia/version/latest/graphql?query=%7B%0A%09pools+%7B%0A++++id%0A%09++tokens(%0A++++++orderBy:+index%0A++++)+%7B%0A%09++++address%0A%09++%7D%0A%09%7D%0A%7D%0A) query.

To be clear: we could move `weights` to a `PoolToken` entity, add `type` and `version` to `Pool`, etc, in the future, if that makes sense. I had made it simple before and been testing how these changes affects syncing and re-deployments. Just to add some color, having the `type` and `version` at `Factory` might allow us to add new factories without re-deploying the Subgraph if they're already supported (think we want to add a WeightedV2) and that'd be very powerful.

**Comment by franzns** [comment]
Having type and version at Factory level is not a problem from our side. As long as the `Pool` has a relationship to `Factory`.

There are a few fields missing that I would've expected in `Pool`:
- createTime (or is that blockTimestamp on the `Pool` on the vault subgraph?)
- name
- symbol
- yieldFeeExempt for rateprovider

Also for `PoolToken`:
- name
- symbol
- decimals

**Comment by franzns** [comment]
Would it be possible to also have `PoolToken` and `RateProvider` in the Pools subgraph instead of vault? This way we could get all pool related params from the pools subgraph.

**Comment by mendesfabio** [comment]
adding the fields you mentioned today. regarding having or moving `PoolToken` and `RateProvider` to the Pools SG, do you mean having just the addresses and name, symbol, etc? Because what we're trying to do it separate pool tokens accounting from pools math/logic. Goal is for the Pools SG to be lightweight so re-deploying with grafting isn't a problem at all.

If we agree that data should live there I have to think a bit how to do it. For instance - I probably would not add Vault as data source and track events from it, it's probably faster to just do on-chain calls as we're already tracking the factories `PoolCreated` events.

**Comment by franzns** [comment]
I'd only need the static data such as addresses, names etc. No balances

**Comment by mendesfabio** [comment]
> Having type and version at Factory level is not a problem from our side. As long as the `Pool` has a relationship to `Factory`.
> 
> There are a few fields missing that I would've expected in `Pool`:
> 
> * createTime (or is that blockTimestamp on the `Pool` on the vault subgraph?)
> * name
> * symbol
> * yieldFeeExempt for rateprovider
> 
> Also for `PoolToken`:
> 
> * name
> * symbol
> * decimals

I've added these fields to the Vault Subgraph -- see this [query](https://api.studio.thegraph.com/proxy/31386/balancer-v3-sepolia/version/latest/graphql?query=%7B%0A%09pools+%7B%0A%09++id%0A++++name%0A++++symbol%0A++++address%0A%09%7D%0A++poolTokens+%7B%0A++++id%0A++++name%0A++++symbol%0A++++decimals%0A++++address%0A++++isExemptFromYieldProtocolFee%0A++%7D%0A%7D%0A) as reference. We can discuss about moving some data to Pools SG tomorrow but I'm still afraid of adding Vault as a datasource to it. I also found some getters that are missing at Vault-level when pondering about it and will report to SC folks.

**Comment by franzns** [comment]
ah, is `PoolToken` and `Rateprovider` data not emitted on pool creating from the factories?

**Comment by franzns** [comment]
Shouldnt `tokens` on the vault subgraph be required under pool? 

![Image](https://github.com/balancer/backend/assets/93920061/1f6d1708-9b85-4cb2-ae80-eef0bbbf2420)

`[PoolToken!]!` instead of `[PoolToken!]`?

Same with rateProvider

**Comment by franzns** [comment]
Same with rateprovider

**Comment by mendesfabio** [comment]
> ah, is `PoolToken` and `Rateprovider` data not emitted on pool creating from the factories?

exactly, Vault emits `PoolRegistered` with all information (pool, factory, tokenConfig[], etc) but the `PoolCreated` from Factory only gives us the pool address

> Shouldnt tokens on the vault subgraph be required under pool?

yes, should be, will push a fix

**Comment by franzns** [comment]
Factory needs an address

**Comment by franzns** [comment]
In v2 we had pool owners, the address that could change the swap fee. Is that available in v3 as well?

**Comment by franzns** [comment]
Can we also get the initial swapFee that is set on the pool?

**Comment by franzns** [comment]
Will the price rate be added to the poolTokens ?

**Comment by mendesfabio** [comment]
> In v2 we had pool owners, the address that could change the swap fee. Is that available in v3 as well?

I think we haven't implemented that yet as I don't see any related field on events, let me ask around.

> Can we also get the initial swapFee that is set on the pool?

sure, I worked on it but couldn't update the deployments given this [incident](https://status.thegraph.com/incidents/f7m68qt9t3qp) 🫠 I thought it would get resolved but it's late here and still not working. will try again tomorrow and let you know.

 > Will the price rate be added to the poolTokens ?

Why do you need it? For V2 we had only the cached value of it so I assumed you maybe query it on-chain?

**Comment by franzns** [comment]
Both swapFee and price rate is not necessary, would just serve as an initial data point when we add the pool to the backend. Although I think both values might be helpful in the pool snapshots

**Comment by franzns** [comment]
Is it possible that we could make it applicable in either subgraph it the pool as a nested pool?

edit: talked to fabio, it's possible and will be added

**Comment by franzns** [comment]
can we add `isPoolInitialized` flag to the subgraph as well?

**Comment by franzns** [comment]
```{
swaps(where:{blockTimestamp_gt: 1707913559}, orderBy: blockTimestamp, orderDirection: asc){
  id
  blockTimestamp
  pool
  transactionHash
  user{
    id
  }
}}
```


returns error: "message": "Null value resolved for non-null field `user`"

**Comment by franzns** [comment]
can we also add tokenInSymbol/tokenOutSymbol to the swap entity?

**Comment by mendesfabio** [comment]
FYI priceRate has been added but we still don't have events for it so I just set 1 as initial/default value. I've addressed most of your comments, ty!

**Comment by franzns** [comment]
> FYI priceRate has been added but we still don't have events for it so I just set 1 as initial/default value. I've addressed most of your comments, ty!

Thanks a lot!

I dont see priceRate anywhere, where did you add it to?

**Comment by mendesfabio** [comment]
the last version ended up failing, just re-deployed! field is at `PoolToken` entity
