### ISSUE TITLE
SOR issue with scientific notation

### ISSUE THREAD

**Issue by gmbronco** [balancer/backend#781]
Cannot convert 9179397209986126e-7 to a BigInt

modules/sor/sorV2/sorPathService.js

queryOutput: {
                        swapKind,
                        expectedAmountOut: outputAmount,
                    },
                    slippage: sdk_1.Slippage.fromPercentage(`${parseFloat(callDataInput.slippagePercentage)}`),
                    deadline: callDataInput.deadline ? BigInt(callDataInput.deadline) : 999999999999999999n,
                });

fails on slippage

https://skloon.sentry.io/issues/5583351199/?environment=multichain-main&project=4504774210158592&query=start%3D2024-08-12T09%3A25%3A00%26end%3D2024-08-12T15%3A47%3A31%26groupStatsPeriod%3Dauto&referrer=alerts-related-issues-issue-stream

**Comment by brunoguerios** [comment]
I can't open the sentry report - looks like I don't have access
I'll create a PR with something that I believe can fix the issue, but I didn't actually test it.
If you could provide a way to reproduce the issue, I can double check on my end.
Or, since the fix is quite trivial, you can replicate and test on your end.
